services:
  proposal-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/proposal-app'
      - 'SPRING_DATASOURCE_USERNAME=myuser'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
      - 'SPRING_RABBITMQ_HOST=rabbit-mq'
      - 'SPRING_RABBITMQ_PORT=5672'
      - 'SPRING_RABBITMQ_USERNAME=guest'
      - 'SPRING_RABBITMQ_PASSWORD=guest'
    depends_on:
      rabbit-mq:
        condition: service_healthy
  notification-app:
    build:
      context: ../Notification-App
      dockerfile: Dockerfile
    environment:
      - 'SPRING_RABBITMQ_HOST=rabbit-mq'
      - 'SPRING_RABBITMQ_PORT=5672'
      - 'SPRING_RABBITMQ_USERNAME=guest'
      - 'SPRING_RABBITMQ_PASSWORD=guest'
    depends_on:
      rabbit-mq:
        condition: service_healthy
  credit-analysis-app:
    build:
      context: ../Credit-Analysis-App
      dockerfile: Dockerfile
    environment:
      - 'SPRING_RABBITMQ_HOST=rabbit-mq'
      - 'SPRING_RABBITMQ_PORT=5672'
      - 'SPRING_RABBITMQ_USERNAME=guest'
      - 'SPRING_RABBITMQ_PASSWORD=guest'
    depends_on:
      rabbit-mq:
        condition: service_healthy
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=proposal-app'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    # volumes:
    #   - ./db.sql:/docker-entrypoint-initdb.d/db.sql
  rabbit-mq:
    image: rabbitmq:3-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - '5672:5672'
      - '15672:15672'
